### ISSUE TITLE
Exclude image in charactername

### ISSUE THREAD

**Issue by DerJaybe** [Wendy-Nam/RenPy-Lipsync-Plugin#3]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/story/ch0.rpy", line 29, in script
    $ lipsync(but, "01.ogg", "“What the heck is this?”")
  File "game/story/ch0.rpy", line 29, in <module>
    $ lipsync(but, "01.ogg", "“What the heck is this?”")
  File "game/lip-sync-plugin/lipsync_module.rpy", line 30, in lipsync
    load_lipsync_data(character_name, audio_track)  # Load lipsync data based on the audio track
  File "game/lip-sync-plugin/lipsync_module.rpy", line 20, in load_lipsync_data
    lipsync_text = renpy.file(file_path).read().decode("utf-8")
OSError: Couldn't find file 'lip-sync-plugin/lip-sync-data/BATTLER USHIROMIYA {image=gui/wing.png}/01.txt'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/story/ch0.rpy", line 29, in script
    $ lipsync(but, "01.ogg", "“What the heck is this?”")
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story/ch0.rpy", line 29, in <module>
    $ lipsync(but, "01.ogg", "“What the heck is this?”")
  File "game/lip-sync-plugin/lipsync_module.rpy", line 30, in lipsync
    load_lipsync_data(character_name, audio_track)  # Load lipsync data based on the audio track
  File "game/lip-sync-plugin/lipsync_module.rpy", line 20, in load_lipsync_data
    lipsync_text = renpy.file(file_path).read().decode("utf-8")
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\exports.py", line 2608, in file
    return open_file(fn, encoding=encoding)
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\exports.py", line 2590, in open_file
    rv = renpy.loader.load(fn, directory=directory)
  File "D:\RenPy\renpy-8.0.3-sdk\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'lip-sync-plugin/lip-sync-data/BATTLER USHIROMIYA {image=gui/wing.png}/01.txt'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
Umineko: When They Cry - Witch's Promise 1.0
Wed Sep 13 18:12:50 2023
[/code]

Code should exclude/ignore {image=gui/wing.png} because you can't put a / in a folder name

**Comment by Wendy-Nam** [comment]
can you please send me the structure of your directory?
first, voice file should be located like this before the lipsync data generation.

`audio/voice/character_name/voice_file.ogg`

so the generated data file would be displayed as follows:

`lip-sync-data/character_name/voice_file.txt`

**Comment by Wendy-Nam** [comment]
It would be also helpful if you can send me your script.rpy file

**Comment by Wendy-Nam** [comment]
oh i got your point. I will try my best to make changes in 5 minutes.

**Comment by Wendy-Nam** [comment]
Hello, Code(`generate_lipsync_data.py`, `lipsync_module.rpy`) is updated now. I'd be grateful if you check them out.

**Comment by DerJaybe** [comment]
Looks good. Question is there support for more than one pose? If yes, how can I set this up?

**Comment by Wendy-Nam** [comment]
Do you mean enabling to change the pose during the lipsync animation?

**Comment by Wendy-Nam** [comment]
If you simply just need changing pose within the dialogue, not during the lipsync, you can simply use layered images. layered image is a stack of floating images. so you can define the group of base images (pose) to change different pose easily
Actually my program is designed to use layerd images

**Comment by DerJaybe** [comment]
Okay, another question is it possible to extend dialogue with extend "text" while using $ lipsync?

**Comment by Wendy-Nam** [comment]
To be honest, it is one of my milestones for now. It is not possible to use extend in my program. Yet i'm planning to refactor my code more native by overriding classes in renpy framework. But it would take some extra time i guess.

**Comment by DerJaybe** [comment]
My idea is to take out the text render function and use the normal one from renpy itself, so that $ lipsync only plays the audio and does not render the text. That way you could also use extend quite simply. I think rendering text a bit too much, the normal say screen is also sufficient.

**Comment by Wendy-Nam** [comment]
thanks for your helpful suggestion. I will definitely consider them. I will try to make changes within few days
